name: Discount Service CD

on:
  workflow_run:
    workflows: ["Discount Service CI"]
    types:
      - completed
    branches:
      - develop
      - main

jobs:
  deploy-to-qa:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    environment: qa
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      run: |
        cd terraform/qa
        terraform init \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=discount-service/terraform.tfstate" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="role_arn=${{ secrets.AWS_ROLE_TO_ASSUME }}"
    
    - name: Terraform Plan
      run: |
        cd terraform/qa
        terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="aws_role_arn=${{ secrets.AWS_ROLE_TO_ASSUME }}" \
          -var="db_username=${{ secrets.DB_USERNAME }}" \
          -var="db_password=${{ secrets.DB_PASSWORD }}" \
          -var="service_name=discount-service" \
          -var="environment=qa" \
          -var="vpc_id=${{ secrets.VPC_ID }}" \
          -var="subnet_ids=${{ secrets.SUBNET_IDS }}" \
          -var="docker_image=${{ secrets.ECR_REPOSITORY_URL }}/billing-discount-service:${{ github.sha }}" \
          -out=tfplan
    
    - name: Terraform Apply
      run: |
        cd terraform/qa
        terraform apply -auto-approve tfplan
    
    - name: Update Discount Service in ECS
      run: |
        aws ecs update-service --cluster billing-qa --service discount-service --force-new-deployment

  create-pr-for-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: deploy-to-qa
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Create Pull Request to main
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Deploy discount-service to production
        title: Deploy Discount Service to Production
        body: |
          This PR is automatically generated to deploy the latest QA-approved Discount Service to production.
          
          ## Changes included
          
          - Automated deployment from develop branch
          - Last commit: ${{ github.sha }}
          
          ## QA Validation
          
          - [x] Deployed to QA environment
          - [x] Passed all CI tests
          
          Please review and approve to deploy to production.
        branch: deploy-discount-service-to-prod
        base: main
        labels: automated-pr, deploy-to-prod, discount-service
        draft: false
        reviewers: ${{ secrets.PROD_REVIEWERS }}

  deploy-to-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      run: |
        cd terraform/prod
        terraform init \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=discount-service/terraform.tfstate" \
          -backend-config="region=${{ secrets.AWS_REGION }}" \
          -backend-config="role_arn=${{ secrets.AWS_ROLE_TO_ASSUME }}"
    
    - name: Terraform Plan
      run: |
        cd terraform/prod
        terraform plan \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="aws_role_arn=${{ secrets.AWS_ROLE_TO_ASSUME }}" \
          -var="db_username=${{ secrets.DB_USERNAME }}" \
          -var="db_password=${{ secrets.DB_PASSWORD }}" \
          -var="service_name=discount-service" \
          -var="environment=prod" \
          -var="vpc_id=${{ secrets.VPC_ID }}" \
          -var="subnet_ids=${{ secrets.SUBNET_IDS }}" \
          -var="docker_image=${{ secrets.ECR_REPOSITORY_URL }}/billing-discount-service:${{ github.sha }}" \
          -out=tfplan
    
    - name: Terraform Apply
      run: |
        cd terraform/prod
        terraform apply -auto-approve tfplan
    
    - name: Update Discount Service in ECS
      run: |
        aws ecs update-service --cluster billing-prod --service discount-service --force-new-deployment
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: discount-service-v${{ github.run_number }}
        name: Discount Service Production Release v${{ github.run_number }}
        body: |
          Discount Service Production release v${{ github.run_number }}
          
          Deployed commit: ${{ github.sha }}
          Deployment date: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
